recipe.yml

Adds a step in the vib recipe to modify `/usr/share/accountsservice/user-templates/{administrator,standard}` to contain `Session=firstsetup`, setting the first setup session as a default for every new user.
This is requires another PR in first-setup, which has not been opened yet, and can only be merged once the PR in first-setup is merged to ensure everything works correctly.
Fixes https://github.com/Vanilla-OS/first-setup/issues/197

Set firstsetup session as default for new users

---

includes.container/etc/vso/fdroid.toml
includes.container/etc/vso/izzyondroid.toml
includes.container/usr/share/vso/apx/stacks/vso-waydroid.yaml

Adds the waydroid configuration files for vanilla-system-operator to ensure that users are able to use the waydroid integration properly.
This currently only adds the files directly through `includes.container`, but we should consider changing this to be automated through a module in the future.

Add waydroid configuration files

---

modules/00-vanilla-apx-gui.yml
modules/00-vanilla-desktop-base.yml
modules/00-vanilla-first-setup.yml
modules/00-vanilla-system-operator.yml
modules/100-accessibility.yml
modules/110-fonts.yml
modules/120-network.yml
modules/140-password.yml
modules/160-utilities.yml
modules/20-gnome-core.yml
modules/200-gnome-common.yml
modules/210-libs-extra.yml
modules/30-gnome-essentials.yml
modules/40-gnome-appearance.yml
modules/60-media.yml
modules/90-3d-utils.yml

- Rearrange packages in alphabetical order.
- Add `libblockdev-crypto3` to libs-extra for LUKS (decryption) as suggested by @axtloss.
- ~Move `optipng` from the desktop base to the utilities module.~ (Edit. Reverted this change after failing CI, seems like we use it to optimize first setup assets)
- Remove `inkscape` from the desktop base as suggested by @taukakao.

cleanup: rearrange packages, add libblockdev-crypto3

---

includes.container/etc/modules.load.d/waydroid.conf
includes.container/etc/udev/rules.d/99-waydroid.rules
modules/02-waydroid-modules.yml
recipe.yml

Adds Binder and Ashmem kernel modules to ensure that waydroid functions properly.
Closes #14

feat:[close #14] add binder+ashmem modules for waydroid

---

.github/workflows/vib-build.yml
.github/workflows/vib-pr.yml
includes.container/usr/sbin/init
recipe.yml

Adds the fsguard module to enable FsGuard in desktop-image.

feat: add fsguard module

---

includes.container/fsguard_config.patch
recipe.yml

Uses a custom FsGuard configuration file to account for the fact that /FsGuard is in /.system/

Fix: use custom fsguard config to account for .system

---

recipe.yml

This command would fail with https://github.com/Vanilla-OS/core-image/pull/26 which is why it needs to be removed to ensure builds still complete successfully

fix: remove ld preload step

---

modules/00-vanilla-sideload.yml

Setting it in /etc/skel/ makes it the default for every new user.

sets sideload as the default for debian packages

---

includes.container/usr/lib/systemd/system/user@.service

This PR attempts to fix #66 by reducing the Systemd timeout from 120s to 60s. This may not look like a proper solution, but it's exactly what SIlverblue did a while back when they had this issue so...

fix:[close #66] Reduce shutdown delay

---

includes.container/usr/share/glib-2.0/schemas/90-vanilla-os-lock.gschema.override

The commit was not only removing the lock screen for the vanilla user. Instead, it was removing the lock screen for all users.
This should be reverted since it's causing #82 
Closes #82 
Reopens #68 
A better solution for #68 would probably require setting it only for the vanilla user or only setting it through the installer.

reverts "fix[close #68]: Remove the default password"

---

includes.container/usr/lib/systemd/system/clear-first-setup-steps.service

Systemd does not use a shell by default so it will not recognize the ">" operator.

runs systemd exec command in shell

---

includes.container/usr/sbin/init

This commit improves the Bash script by introducing the following changes:
1. **Variable Scoping**: Variables within the `failed` function are now declared with `local`. This change confines their scope to the function itself, preventing them from affecting the global environment or interfering with other scripts that might source this file.
2. **Variable Quoting**: All variable expansions have been quoted properly. This enhancement prevents issues related to word splitting and globbing, which are common sources of bugs in shell scripts, especially when variables may contain spaces or special shell characters.
These modifications enhance the robustness, readability, and maintainability of the script, ensuring that it adheres to best practices for shell scripting. These changes are …

Refactor shell script to enhance variable scoping and security

---

recipe.yml

Upgrades flatpak to 1.14.6, which contains the patch for [cve-2024-32462](https://github.com/flatpak/flatpak/security/advisories/GHSA-phv6-cpc2-2fgj)

fix: Bump flatpak to 1.14.6

---

includes.container/etc/udev/rules.d/99-waydroid.rules

The `NAME` parameter does not work for kernel module rules

fix waydroid udev rules

---

includes.container/usr/bin/waydroid

Adds a "fake" waydroid script to the host so that gnome shows the waydroid desktop entries

fix: Show waydroid desktop entries

---

modules/80-printers.yml

Adds packages for Brother, Epson, and HP laser printers that are not part of CUPS.

feat: Add drivers for some common printer models

---

includes.container/etc/systemd/user/apx-vso-pico.service

Adds a systemd unit for managing apx-vso-pico, which automatically starts the container on startup and shuts it down on poweroff. When enabled by the user (new installations should do by default with first-setup), this service avoids having to wait for the container to start when opening a terminal for the first time, as well as drastically reduces the poweroff time.

feat: systemd unit for apx-vso-pico

---

includes.container/etc/systemd/user/apx-vso-pico.service
recipe.yml

If the container is started before the user has an internet connection, the container won't be able to connect to the internet until restarted. This commit removes the autostart part, while leaving the shutdown when graphical-session.target is stopped.

fix: remove apx-vso-pico autostart

---

includes.container/usr/lib/systemd/system/abroot-mount-fstab.service

Since the user fstab file is loaded after systemd has started, new swap entries are ignored.
This adds a manual swapon call to when the user fstab file is available.
Fixes #124

fix [#124]: adds support for swap from fstab

---

.gitignore

Adds `plugins` dir to `.gitignore` as that should be excluded from VCS

fix:[close #133] Add plugins dir to .gitignore

---

modules/41-gnome-46.yml
recipe.yml

Tempfix: Add module to pull gnome components from Debian experimental.
~~This is currently hardcoded while I put together a solution for consistently pulling the same version. Will update the description and remove the draft status when I have that implemented.~~ We are now using the snapshots of packages from the releases of https://github.com/Vanilla-OS/debian-gnome-debs.
This PR:
- Adds modules for gnome 46
- Updates recipe.yml for new module
closes #132

feat: add module for GNOME 46 components

---

modules/41-gnome-46.yml

- Change download location to `/tmp/gnome-46`

fix: download debs to /tmp/gnome-46

---

includes.container/etc/sysctl.d/core-pattern.conf

closes #141 
Tested locally with the following steps:
**/etc/sysctl.d/core-pattern.conf**
```
kernel.core_pattern = /var/tmp/core.%e.%p.%h.%t
```
**reload params**
```
sysctl --system
```
**crash.c**
```c
#include <stdio.h>
#include <stdlib.h>
int main() {
int *ptr = NULL;
*ptr = 42;
return 0;
```
**run the crasher**
```
gcc -o crash crash.c
```
**check for dumps in /var/tmp/core**

fix[close #141]: Core dumps gets stored in random places

---

includes.container/usr/lib/systemd/user/vso-tasks-rotation.service
modules/00-vanilla-system-operator.yml

closes #136 
This removes the need for creating a autostart file directly into the home directory with vanilla system operator
https://github.com/Vanilla-OS/vanilla-system-operator/blob/05757fb763d43645db2c6ce8b4796f831f928318/core/tasks.go#L271-L303

feat: a service for vso tasks rotation

---

.github/workflows/vib-build.yml

The old version had a bug that triggered FsWarn on every boot.
Tested in a VM with a forked image.
Fixes #153

fix: upgrade vib-fsguard to v1.5.2

---

includes.container/usr/share/init.d/010-fsguard.sh
recipe.yml

This PR depends on this: https://github.com/Vanilla-OS/core-image/pull/57
This adjust the FsWarn init system for the new structure.

adapts fswarn script to new init system

---

modules/210-libs-extra.yml

This PR adds the `gnome-epub-thumbnailer` package which renders eBook thumbnails in Nautilus.
- https://packages.debian.org/sid/gnome-epub-thumbnailer
- https://www.omgubuntu.co.uk/2024/07/how-to-display-ebook-thumbnails-in-nautilus

feat: add gnome-epub-thumbnailer

---

includes.container/usr/bin/wait-for-connection
includes.container/usr/lib/systemd/user/vso-pre-run.service
modules/00-vanilla-system-operator.yml

Since user sysd units cannot depend on system targets, I made a custom script that uses `nmcli` to check for the connectivity, then used it as a condition in `ExecStartPre`.
Tested on a VM:
- installed the unit
- restarted the VM
- I noticed that Vso didn't show the distrobox initialization process but the prompt directly

feat[close #169]: pre-run vso shell at boot if already initialized

---

.github/workflows/release.yml
modules/00-vanilla-apx-gui.yml
modules/00-vanilla-backgrounds.yml
modules/00-vanilla-desktop-base.yml
modules/00-vanilla-first-setup.yml
modules/00-vanilla-gnome-default-settings.yml
modules/00-vanilla-sideload.yml
modules/00-vanilla-system-operator.yml
modules/00-vanilla-tour.yml
modules/00-vanilla-updates-utility.yml
modules/02-waydroid-modules.yml
modules/10-vanilla-abroot-rollback-notifier.yml
modules/131-plymouth-theme-vanilla.yml
modules/170-gnome-software-vso-plugin.yml
modules/21-gnome-control-center.yml
recipe.yml

This PR performs major changes making the desktop image ready for the 28th stable release.
- Migrate Git sources to tagged releases.
- Migrate Tar sources to tagged releases with checksum verification.
- Replace a few Dpkg modules to use pre-build DEBs from release assets fetched using the file source type along with checksum verification.

feat (major): migrate modules for stable

---

includes.container/usr/lib/systemd/user/vso-pre-run.service

Systemd units don't run inside a shell by default so this can't be used.
I removed it entirely since the ls command should never just through an error without a good reason.
(The systemd service still starts the container but the ls command will through an error because "ls || true" is not a valid command)

remove invalid syntax from systemd service

---

modules/00-vanilla-first-setup.yml
modules/131-plymouth-theme-vanilla.yml
modules/210-libs-extra.yml

- Bump first setup version to use the new logo.
- Bump Plymouth version to get the recent fix from Tau.
- Add JPEG-XL pixbuf dep because GNOME backgrounds are in that format but the Debian package doesn't list/install it as a dep.
Post the change the solid backgrounds (non-SVG, PNG ones) will be fixed and it will be something like:

fix: add dep, bump packages

---

modules/00-vanilla-first-setup.yml

Due to a bug introduced in version 2.2.2, the first user created during the first setup, cannot proceed with the configuration.

chore: downgrade first-setup to v2.2.1

---

includes.container/usr/lib/systemd/user/vso-pre-run.service

While the pre run does work systemd thinks it failed. Additionally, the output is confusing.

improves vso pre run

---

modules/30-gnome-essentials.yml

This package is needed to allow extensions to run on nautilus

Consider adding python3-nautilus (nautilus extensions support)

---

includes.container/usr/share/polkit-1/rules.d/org.vanillaos.vso.rules

Podman can be used to aquire full access to the root user so unrestricted access is dangerous.

removes polkit rule for security reasons

---

includes.container/usr/share/glib-2.0/schemas/90-nautilus-terminal-rightclick.gschema.override
modules/35-nautilus-terminal-rightclick.yml
recipe.yml

using https://github.com/Stunkymonkey/nautilus-open-any-terminal as the script, tag 0.6.0

Added support for opening terminal in nautilus

---

includes.container/etc/gdm3/greeter.conf.d/1-disable-smartcard-login.conf

Disables smartcard authentication in gdm3 by default which is an issue for users with yubikeys or similar smartcards.
The feature is only useful for corporate networks, which Vanilla OS isn't targeting currently and which would create unique images either way
https://gitlab.gnome.org/GNOME/gdm/-/issues/877

fix: disable smartcard authentication on gdm3

---

modules/00-vanilla-apx-gui.yml
modules/00-vanilla-updates-utility.yml
modules/10-vanilla-abroot-rollback-notifier.yml

- add buildflag to set install prefix for apx-gui
- add buildflag to set install prefix for vanilla-updates-utility
- add buildflag to set install prefix for abroot-rollback-notifier
this will require a new vib release 
closes #175

fix: update meson install prefix

---

includes.container/usr/share/glib-2.0/schemas/90-nautilus-terminal-rightclick.gschema.override

the nautilus extension assumes that the executable of blackbox is "blackbox", but for us it's "blackbox-terminal"

fixes nautilus open in shell

---

includes.container/usr/share/init.d/010-fsguard.sh

When the user uses the abroot pkg functionality, the image that's being used is unclean, so it can not be properly checked with FSGuard.
Fixes #192

fix [#192]: disables FSGuard on unclean systems

---

includes.container/usr/share/glib-2.0/schemas/90-gnome-accent-color.gschema.override

This sets the default accent color to yellow to fit the VOS look better.
The user can still change this color in the control center.
Tested in a VM.
Fixes #52

Fix [#52]: creates override for the gnome accent color

---

modules/300-hide-image-magick.yml
recipe.yml

Since ooo-thumbnailer depends on imagemagick, we can't just remove it so the best thing to do is just hide the desktop entry.

hides imagemagick desktop entry
